Add minutes 24th SG meeting
etf-validator/governance pull request #97
Opened 2020-09-07 13:22 UTC by MarcoMinghini

Signed-off-by: Marco Minghini <marco.minghini86@gmail.com>

2020-09-09 16:48 UTC, jonherrmann requested changes
Thanks for the minutes, Marco. I have added 3 comments for EIP 57.

2020-09-09 16:48 UTC, jonherrmann commented on Meetings/SG/20200806.md
> +  - [ ] ii to integrate the new v. 2 of the library in the ETF BaseX test driver.
The work was already completed before the 24 SG meeting. Therefore there is no longer a task for this.

2020-09-09 16:48 UTC, jonherrmann commented on Meetings/SG/20200806.md
> +  - once the approach is proven to work for v. 1 of GmlGeoX, in the future the same approach can be extended to v. 2 (again by first discussing the approach in a new EIP).
I made a note that we wanted to open 2 EIPs. One for v1 (which we did) and one for V2, which will be just a draft for now.

Additionally a Pull Request for the v1 change should be created in the [etf-gmlgeox repo](https://github.com/etf-validator/etf-gmlgeox/pulls).

2020-09-10 19:18 UTC, jonherrmann approved these changes

2020-09-10 20:18 UTC, cportele approved these changes

2020-09-23 06:48 UTC, merged